library("ggplot2")
normdata = read.csv("norm_prepost_rates_SpinyStellate_20.0ms_window.csv")
lognormdata = read.csv("lognorm_prepost_rates_SpinyStellate_20.0ms_window.csv")
qplot(normdata$dbcount, normdata$premean)
qplot(lognormdata$dbcount, lognormdata$premean)
qplot(normdata$dbcount, normdata$postmean)
qplot(lognormdata$dbcount, lognormdata$postmean)
qplot(normdata$premean, normdata$postmean)
qplot(log(normdata$premean), log(normdata$postmean))
qplot(lognormdata$premean, lognormdata$postmean)
qplot(log(lognormdata$premean), log(lognormdata$postmean))
normdata["distribution"] <- "normal"
lognormdata["distribution"] <- "lognormal"
combined <- rbind(normdata, lognormdata)
head(combined)
summary(combined)
combined$distribution <- factor(combined$distribution)
summary(combined)
ks.test(normdata[normdata$dbcount == 30,]$postmean, lognormdata[lognormdata$dbcount == 30,]$postmean)
ks.test(normdata[normdata$dbcount == 40,]$postmean, lognormdata[lognormdata$dbcount == 40,]$postmean)
ks.test(normdata[normdata$dbcount == 50,]$postmean, lognormdata[lognormdata$dbcount == 50,]$postmean)
ks.test(normdata[normdata$dbcount == 60,]$postmean, lognormdata[lognormdata$dbcount == 60,]$postmean)
ks.test(normdata[normdata$dbcount == 70,]$postmean, lognormdata[lognormdata$dbcount == 70,]$postmean)
ks.test(normdata[normdata$dbcount == 80,]$postmean, lognormdata[lognormdata$dbcount == 80,]$postmean)
